name: Deliver
on:
  workflow_run:
    workflows: ["Dockerize"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: danielr1996/kubectl-action@1.0.0
        name: Deploy
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: set image --record deployment/space-invaders space-invaders=avshidocker/space_invaders:latest
      - uses: danielr1996/kubectl-action@1.0.0
        name: Update
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: set image --record deployment/space-invaders space-invaders=avshidocker/space_invaders
