name: Dockerize

on:
  workflow_run:
    workflows: ["Front End Tests", "Lint Code Base Action"]
    branches: [main]
    types:
      - completed
  # push:
  #   branches:
  #     - "master"
  #     - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: avshidocker/space_invaders:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
