name: Lint Code Base Action
on:
  push:
jobs:
  build:
    name: Lint Code Base Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_BASH: true
          VALIDATE_CSS: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          #VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_XML: true
