name: run-my-tests
on: [push]
jobs:
  run-my-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: pip install django
      - run: npm ci
      - run: python manage.py runserver & sleep 10 && npm test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/j*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
      
